# Generated by Django 4.0.1 on 2022-08-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=16, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
            ],
        ),
    ]
