# Generated by Django 4.0.1 on 2022-08-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=24, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='рейтинг'),
        ),
    ]
