# Generated by Django 4.0.1 on 2022-08-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='static/main/img/198411517.jpg', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
