# Generated by Django 4.0.1 on 2022-08-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
