# Generated by Django 4.0.1 on 2022-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='determined',
            name='successfully',
            field=models.BooleanField(default=False, verbose_name='Успешное решение'),
        ),
    ]
