# Generated by Django 4.0.1 on 2023-02-03 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='compet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.competition'),
            preserve_default=False,
        ),
    ]
