# Generated by Django 4.0.1 on 2022-09-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_determined_successfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='determined',
            name='error_type',
            field=models.CharField(default=0, max_length=30, verbose_name='Ошибка'),
            preserve_default=False,
        ),
    ]
