# Generated by Django 4.0.1 on 2023-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_competition_tasks_task_compet'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='document',
            field=models.FileField(default=0, upload_to='comp_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='error',
            field=models.CharField(default=0, max_length=30, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество полученых очков'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
