# Generated by Django 4.0.1 on 2022-09-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_determined_error_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='determined',
            old_name='error_type',
            new_name='error',
        ),
    ]
