# Generated by Django 4.0.1 on 2023-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_attempt_document_alter_attempt_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='error',
            field=models.CharField(default='-', max_length=30, verbose_name='Ошибка'),
        ),
    ]
