# Generated by Django 4.0.1 on 2022-11-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='File',
        ),
    ]
