# Generated by Django 4.1.6 on 2023-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_attempt_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rating_points',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='tried_users',
        ),
        migrations.AddField(
            model_name='competition',
            name='amount_of_users',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пользователей'),
            preserve_default=False,
        ),
    ]
