# Generated by Django 4.0.1 on 2022-11-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_file_creation_date_file_solo_alter_article_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='solo',
        ),
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(null=True, upload_to='img/'),
        ),
    ]
