# Generated by Django 4.1.6 on 2023-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_competition_rating_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='amount_of_users',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество пользователей'),
        ),
    ]
