# Generated by Django 4.0.1 on 2022-11-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_file_solo_alter_file_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.article'),
        ),
    ]
