# Generated by Django 4.1.6 on 2023-02-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_competition_amount_of_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='condition',
        ),
        migrations.AddField(
            model_name='task',
            name='required_input',
            field=models.TextField(default=0, verbose_name='Входные данные'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='required_output',
            field=models.TextField(default=0, verbose_name='Выходные данные'),
            preserve_default=False,
        ),
    ]
