# Generated by Django 4.0.1 on 2022-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_file_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(null=True, upload_to='article_files/'),
        ),
    ]
