# Generated by Django 4.0.1 on 2022-11-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_task_soft'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытая попытка'),
        ),
    ]
